// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: accounts.sql

package postgres

import (
	"context"
)

const selectAccountByID = `-- name: SelectAccountByID :one
SELECT id, name, nik, email, password, gender, role, avatar, illness_history, created_at, updated_at FROM accounts
WHERE id = $1
LIMIT 1
`

func (q *Queries) SelectAccountByID(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRow(ctx, selectAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Nik,
		&i.Email,
		&i.Password,
		&i.Gender,
		&i.Role,
		&i.Avatar,
		&i.IllnessHistory,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
