// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: posts.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPosts = `-- name: CountPosts :one
SELECT COUNT(id) FROM posts
`

func (q *Queries) CountPosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPosts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePost = `-- name: DeletePost :execrows
DELETE FROM posts
WHERE id = $1
`

func (q *Queries) DeletePost(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePost, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertPost = `-- name: InsertPost :exec
INSERT INTO posts (
    id, account_id, topic_id, title, content, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
`

type InsertPostParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
	TopicID   uuid.UUID
	Title     string
	Content   string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) InsertPost(ctx context.Context, arg InsertPostParams) error {
	_, err := q.db.Exec(ctx, insertPost,
		arg.ID,
		arg.AccountID,
		arg.TopicID,
		arg.Title,
		arg.Content,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const selectAllPosts = `-- name: SelectAllPosts :many
SELECT p.id, p.account_id, p.topic_id, p.title, p.content, p.created_at, p.updated_at, a.username AS account_username, t.name AS topic_name
FROM posts p
JOIN accounts a ON p.account_id = a.id
JOIN topics t ON p.topic_id = t.id
ORDER BY p.created_at DESC
`

type SelectAllPostsRow struct {
	ID              uuid.UUID
	AccountID       uuid.UUID
	TopicID         uuid.UUID
	Title           string
	Content         string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	AccountUsername string
	TopicName       string
}

func (q *Queries) SelectAllPosts(ctx context.Context) ([]SelectAllPostsRow, error) {
	rows, err := q.db.Query(ctx, selectAllPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectAllPostsRow{}
	for rows.Next() {
		var i SelectAllPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TopicID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccountUsername,
			&i.TopicName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectAllPostsPaginated = `-- name: SelectAllPostsPaginated :many
SELECT p.id, p.account_id, p.topic_id, p.title, p.content, p.created_at, p.updated_at, a.username AS account_username, t.name AS topic_name
FROM posts p
JOIN accounts a ON p.account_id = a.id
JOIN topics t ON p.topic_id = t.id
ORDER BY p.created_at DESC
LIMIT $1
OFFSET $2
`

type SelectAllPostsPaginatedParams struct {
	Limit  int32
	Offset int32
}

type SelectAllPostsPaginatedRow struct {
	ID              uuid.UUID
	AccountID       uuid.UUID
	TopicID         uuid.UUID
	Title           string
	Content         string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	AccountUsername string
	TopicName       string
}

func (q *Queries) SelectAllPostsPaginated(ctx context.Context, arg SelectAllPostsPaginatedParams) ([]SelectAllPostsPaginatedRow, error) {
	rows, err := q.db.Query(ctx, selectAllPostsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectAllPostsPaginatedRow{}
	for rows.Next() {
		var i SelectAllPostsPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TopicID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccountUsername,
			&i.TopicName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectPostByID = `-- name: SelectPostByID :one
SELECT p.id, p.account_id, p.topic_id, p.title, p.content, p.created_at, p.updated_at, a.username AS account_username, t.name AS topic_name
FROM posts p
JOIN accounts a ON p.account_id = a.id
JOIN topics t ON p.topic_id = t.id
WHERE p.id = $1
LIMIT 1
`

type SelectPostByIDRow struct {
	ID              uuid.UUID
	AccountID       uuid.UUID
	TopicID         uuid.UUID
	Title           string
	Content         string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	AccountUsername string
	TopicName       string
}

func (q *Queries) SelectPostByID(ctx context.Context, id uuid.UUID) (SelectPostByIDRow, error) {
	row := q.db.QueryRow(ctx, selectPostByID, id)
	var i SelectPostByIDRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TopicID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountUsername,
		&i.TopicName,
	)
	return i, err
}

const selectPostsByAccountID = `-- name: SelectPostsByAccountID :many
SELECT p.id, p.account_id, p.topic_id, p.title, p.content, p.created_at, p.updated_at, a.username AS account_username, t.name AS topic_name
FROM posts p
JOIN accounts a ON p.account_id = a.id
JOIN topics t ON p.topic_id = t.id
WHERE p.account_id = $1
ORDER BY p.created_at DESC
`

type SelectPostsByAccountIDRow struct {
	ID              uuid.UUID
	AccountID       uuid.UUID
	TopicID         uuid.UUID
	Title           string
	Content         string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	AccountUsername string
	TopicName       string
}

func (q *Queries) SelectPostsByAccountID(ctx context.Context, accountID uuid.UUID) ([]SelectPostsByAccountIDRow, error) {
	rows, err := q.db.Query(ctx, selectPostsByAccountID, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectPostsByAccountIDRow{}
	for rows.Next() {
		var i SelectPostsByAccountIDRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TopicID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccountUsername,
			&i.TopicName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectPostsByAccountIDPaginated = `-- name: SelectPostsByAccountIDPaginated :many
SELECT p.id, p.account_id, p.topic_id, p.title, p.content, p.created_at, p.updated_at, a.username AS account_username, t.name AS topic_name
FROM posts p
JOIN accounts a ON p.account_id = a.id
JOIN topics t ON p.topic_id = t.id
WHERE p.account_id = $1
ORDER BY p.created_at DESC
LIMIT $2
OFFSET $3
`

type SelectPostsByAccountIDPaginatedParams struct {
	AccountID uuid.UUID
	Limit     int32
	Offset    int32
}

type SelectPostsByAccountIDPaginatedRow struct {
	ID              uuid.UUID
	AccountID       uuid.UUID
	TopicID         uuid.UUID
	Title           string
	Content         string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	AccountUsername string
	TopicName       string
}

func (q *Queries) SelectPostsByAccountIDPaginated(ctx context.Context, arg SelectPostsByAccountIDPaginatedParams) ([]SelectPostsByAccountIDPaginatedRow, error) {
	rows, err := q.db.Query(ctx, selectPostsByAccountIDPaginated, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectPostsByAccountIDPaginatedRow{}
	for rows.Next() {
		var i SelectPostsByAccountIDPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TopicID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccountUsername,
			&i.TopicName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectPostsByTopicID = `-- name: SelectPostsByTopicID :many
SELECT p.id, p.account_id, p.topic_id, p.title, p.content, p.created_at, p.updated_at, a.username AS account_username, t.name AS topic_name
FROM posts p
JOIN accounts a ON p.account_id = a.id
JOIN topics t ON p.topic_id = t.id
WHERE p.topic_id = $1
ORDER BY p.created_at DESC
`

type SelectPostsByTopicIDRow struct {
	ID              uuid.UUID
	AccountID       uuid.UUID
	TopicID         uuid.UUID
	Title           string
	Content         string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	AccountUsername string
	TopicName       string
}

func (q *Queries) SelectPostsByTopicID(ctx context.Context, topicID uuid.UUID) ([]SelectPostsByTopicIDRow, error) {
	rows, err := q.db.Query(ctx, selectPostsByTopicID, topicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectPostsByTopicIDRow{}
	for rows.Next() {
		var i SelectPostsByTopicIDRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TopicID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccountUsername,
			&i.TopicName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectPostsByTopicIDPaginated = `-- name: SelectPostsByTopicIDPaginated :many
SELECT p.id, p.account_id, p.topic_id, p.title, p.content, p.created_at, p.updated_at, a.username AS account_username, t.name AS topic_name
FROM posts p
JOIN accounts a ON p.account_id = a.id
JOIN topics t ON p.topic_id = t.id
WHERE p.topic_id = $1
ORDER BY p.created_at DESC
LIMIT $2
OFFSET $3
`

type SelectPostsByTopicIDPaginatedParams struct {
	TopicID uuid.UUID
	Limit   int32
	Offset  int32
}

type SelectPostsByTopicIDPaginatedRow struct {
	ID              uuid.UUID
	AccountID       uuid.UUID
	TopicID         uuid.UUID
	Title           string
	Content         string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	AccountUsername string
	TopicName       string
}

func (q *Queries) SelectPostsByTopicIDPaginated(ctx context.Context, arg SelectPostsByTopicIDPaginatedParams) ([]SelectPostsByTopicIDPaginatedRow, error) {
	rows, err := q.db.Query(ctx, selectPostsByTopicIDPaginated, arg.TopicID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectPostsByTopicIDPaginatedRow{}
	for rows.Next() {
		var i SelectPostsByTopicIDPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TopicID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccountUsername,
			&i.TopicName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePost = `-- name: UpdatePost :exec
UPDATE posts
SET
  title = COALESCE($2, title),
  content = COALESCE($3, content),
  updated_at = $4
WHERE id = $1
`

type UpdatePostParams struct {
	ID        uuid.UUID
	Title     pgtype.Text
	Content   pgtype.Text
	UpdatedAt time.Time
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) error {
	_, err := q.db.Exec(ctx, updatePost,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.UpdatedAt,
	)
	return err
}
