// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	InsertAccount(ctx context.Context, arg InsertAccountParams) error
	SelectAccountByID(ctx context.Context, id uuid.UUID) (Account, error)
	SelectAccountByUsername(ctx context.Context, username string) (Account, error)
}

var _ Querier = (*Queries)(nil)
