// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package postgres

import (
	"context"
)

const selectUserByID = `-- name: SelectUserByID :one
SELECT id, name, nik, email, password, gender, role, avatar, illness_history, created_at, updated_at FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) SelectUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, selectUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Nik,
		&i.Email,
		&i.Password,
		&i.Gender,
		&i.Role,
		&i.Avatar,
		&i.IllnessHistory,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
